name: Comment and Close Patched Issues on Tag

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  comment_and_close:
    runs-on: ubuntu-latest
    steps:
      - name: Find and handle patched issues
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                labels: 'patched'
              }
            );

            for (const issue of issues) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `This issue has been patched and is now being closed as of tag **${context.ref.replace('refs/tags/', '')}**.`
              });

              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }
