name: Close issues upon a release.
on:
  release:
    types: [published]

jobs:
  comment-and-close:
    runs-on: ubuntu-latest
    steps:
      - name: Close issues marked as fixed upon a release.
        uses: gcampbell-msft/fixed-pending-release@0.0.9
        with:
          token: ${{ secrets.CLOSE_ISSUE_ON_RELEASE }}
          label: patched
          message: >
            :tada: This issue has now been fixed and is available in [${releaseTag}](${releaseUrl}) :tada:

            This ticket is now closed. If you have any more question, feel free to reply below. If needed,
            the ticket will be re-open for further support.
