name: Deploy Release

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JVM
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: temurin
          cache: 'maven'

      - name: Compile To JAR File
        run: mvn -B validate package

      - name: Check Compiled File
        run: ls -lAh ./target/

      - name: Install xmllint
        run: |
          sudo apt-get update && sudo apt-get install -y libxml2-utils
          xmllint --version

      - name: Acquire App Version
        id: version
        run: |
          version=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          echo "APP_VERSION=$version" >> $GITHUB_OUTPUT

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: compiled
          path: ./target/*.jar

  convert2deb:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: Check version
        run: echo ${{ env.APP_VERSION }}

      - name: Download Artifact
        uses: actions/download-artifact@v3

      - name: Setup JVM
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: temurin

      - name: Convert JAR To DEB
        run: jpackage --input ./compiled --main-jar JavaToExe-${{ env.APP_VERSION }}.jar --main-class me.knighthat.javatoexe.JavaToExe --name JavaToExe --app-version ${{ env.APP_VERSION }}

      - name: Rename DEB File
        run: mv ./*.deb JavaToExe-${{ env.APP_VERSION }}_amd64.deb
        
      - name: Upload DEB
        uses: actions/upload-artifact@v3
        with:
          name: compiled
          path: ./*.deb

  convert2exe:
    runs-on: windows-latest
    needs: compile
    
    steps:
      - name: Check version
        run: echo ${{ env.APP_VERSION }}

      - name: Download Artifact
        uses: actions/download-artifact@v3

      - name: Setup JVM
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: temurin

      - name: Convert JAR To EXE
        run: jpackage --input ./compiled --main-jar JavaToExe-${{ env.APP_VERSION }}.jar --main-class me.knighthat.javatoexe.JavaToExe --name JavaToExe --app-version ${{ env.APP_VERSION }}

      - name: Rename EXE File
        run: mv ./*.exe JavaToExe-${{ env.APP_VERSION }}_x86_64.exe
        
      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: compiled
          path: ./*.exe

  convert2dmg:
    runs-on: macos-latest
    needs: compile

    steps:
      - name: Check version
        run: echo $APP_VERSION

      - name: Download Artifact
        uses: actions/download-artifact@v3

      - name: Setup JVM
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: temurin

      - name: Convert JAR To DMG
        run: jpackage --input ./compiled --main-jar JavaToExe-${{ env.APP_VERSION }}.jar --main-class me.knighthat.javatoexe.JavaToExe --name JavaToExe

      - name: Rename DMG File
        run: mv ./*.dmg JavaToExe-${{ env.APP_VERSION }}.dmg
        
      - name: Upload DMG
        uses: actions/upload-artifact@v3
        with:
          name: compiled
          path: ./*.dmg

  upload:
    runs-on: ubuntu-latest
    needs: [convert2deb, convert2exe, convert2dmg]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: release-assets
          path: ./compiled/*

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./compiled/*
          draft: false
          prerelease: false
          tag_name: beta
          name: "v${{ env.APP_VERSION }}"
          token: ${{ secrets.TEMP_TOKEN }}
